runner:
  npm-groovy-lint:
    cmd: |
      npm-groovy-lint -o log.txt || true
      cat log.txt
    errorformat:
      - '%-P%f'
      - '%*\s%l%*\s%terr%*\s%m'
      - '%*\s%l%*\s%twarn%*\s%m'
      - '%-Q'
    level:
      - warning
      - error