runner:
  npm-groovy-lint:
    cmd: |
      npm-groovy-lint /scripts -o log.txt || true
      cat log.txt
    errorformat:
      - '%-P%f'
      - '%*\s%l%*\s%trror%*\s%m'
      - '%*\s%l%*\s%tarning%*\s%m'
      - '%*\s%l%*\s%tnfo%*\s%m'
      - '%-Q'