name: GitHub Actions - reviewdog

on:
  pull_request:

jobs:
  groovylint:
    runs-on: ubuntu-latest
    container:
      image: docker://nvuillam/npm-groovy-lint
    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache curl git
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run npm-groovy-lint
        run: |
          npm-groovy-lint /scripts -o log.txt || true
          cat log.txt

      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -runners=npm-groovy-lint